/* AUTO-GENERATED by scripts/generate-t-keys.mjs — DO NOT EDIT.
 * Source of truth: src/i18n/messages/uk.json
 * Regenerate: npm run generate-t-keys
 */
import type { ReactNode } from 'react'

export type TranslationValues = Record<string, string | number | Date>
export type RichValues = Record<
	string,
	string | number | Date | ((chunks: ReactNode) => ReactNode)
>

export const TKeys = {
	common: 'common',
	meta: 'meta',
	notFound: 'notFound',
	auth: {
		login: 'auth.login',
		register: 'auth.register',
		forgotPassword: 'auth.forgotPassword',
		resetPassword: 'auth.resetPassword',
	},
	validation: 'validation',
	errors: 'errors',
	nav: 'nav',
	blog: 'blog',
	home: 'home',
	about: 'about',
	privacy: 'privacy',
	contacts: 'contacts',
	webinars: 'webinars',
	paywall: 'paywall',
	payments: 'payments',
	cabinet: {
		studyPlatform: 'cabinet.studyPlatform',
		common: 'cabinet.common',
		personalData: 'cabinet.personalData',
		subscriptions: 'cabinet.subscriptions',
		certificates: 'cabinet.certificates',
		settings: 'cabinet.settings',
		webinars: 'cabinet.webinars',
	},
	screener: 'screener',
	aiAgent: 'aiAgent',
	tradingChat: 'tradingChat',
} as const

export interface MessageShapes {
	'common': {
		loading: string
		user: string
		copyright: string
		addToCart: string
		samplePrice: string
		latestWebinarTitle: string
		latestWebinarSubtitle: string
		watchWebinar: string
		signInToWatch: string
		webinarLabel: string
		vbHeroTitle: (values: RichValues) => ReactNode
		vbHeroSubtitle: (values: RichValues) => ReactNode
		home: string
	}
	'meta': {
		title: string
		description: string
	}
	'notFound': {
		title: string
		description: string
		goHome: string
		myAccount: string
	}
	'auth.login': {
		tabLabel: string
		passwordPlaceholder: string
		consent: string
		submit: string
		forgotPassword: string
		screenerPromo: string
		accountDeleted: string
		passwordResetSuccess: string
	}
	'auth.register': {
		tabLabel: string
		screenerPromo: string
		passwordPlaceholder: string
		passwordRequirementsLabel: string
		confirmPasswordPlaceholder: string
		submit: string
		consent: string
		privacyPolicy: string
		consentSuffix: string
		errorGeneral: string
		errorEmailExists: string
		errorFieldBlank: string
		errorFieldRequired: string
		errorFieldMinChars: string
	}
	'auth.forgotPassword': {
		title: string
		instructions: string
		backToLogin: string
		description: string
		submit: string
		errorGeneral: string
	}
	'auth.resetPassword': {
		title: string
		validating: string
		linkInvalid: string
		requestNewLink: string
		backToLogin: string
		success: string
		signIn: string
		description: string
		newPasswordPlaceholder: string
		confirmPasswordPlaceholder: string
		submit: string
		errorGeneral: string
		showPassword: string
		hidePassword: string
		serverErrorInvalidToken: string
		serverErrorPasswordTooCommon: string
	}
	'validation': {
		firstNameRequired: string
		lastNameRequired: string
		phoneInvalid: string
		solanaInvalid: string
		currentPasswordRequired: string
		minChars: (values: TranslationValues) => string
		passwordsMismatch: string
		newPasswordMustDiffer: string
		emailRequired: string
		emailInvalid: string
		passwordConfirmationRequired: string
		passwordMin8: string
		passwordNeedsUppercase: string
		passwordNeedsLowercase: string
		passwordNeedsDigit: string
		repeatPassword: string
	}
	'errors': {
		invalidCredentials: string
		userNotActive: string
		oldPasswordIncorrect: string
		passwordIncorrect: string
		passwordsMismatch: string
		newPasswordMustDiffer: string
		passwordChangedSuccess: string
		emailChangedSuccess: string
		changePasswordFailed: string
		changeEmailFailed: string
		deleteAccountFailed: string
	}
	'nav': {
		personalData: string
		algoTrading: string
		screener: string
		tradingChat: string
		blog: string
		education: string
		settings: string
		logout: string
		support: string
		academy: string
		privacyPolicy: string
		shopUpper: string
		academyVbUpper: string
		webinarsUpper: string
		aboutUsUpper: string
		blogUpper: string
		menuSets: string
		menuVitaminComplexes: string
		menuMineralComplexes: string
		menuImmunityAntioxidants: string
		menuSoundSleep: string
		menuEmotionalIntelligence: string
		menuWebinars: string
		menuCustomCourse: string
		menuTeam: string
		menuSocialResponsibility: string
		menuContacts: string
	}
	'blog': {
		categoryBody: string
		readMore: string
		sampleDate: string
		title: string
		loading: string
		notFound: string
		notFoundDesc: string
		commentsTitle: string
		commentPlaceholder: string
		send: string
		mentorComment: string
	}
	'home': {
		eBalanceProUpper: string
		whatIsVb: string
		whatIsVbDesc: string
		bodyTitle: string
		mindTitle: string
		spiritTitle: string
		readMore: string
		supplementsTitle: string
		catVitaminComplexes: string
		catMineralComplexes: string
		catImmunityAntioxidants: string
		catEnergyActivity: string
		catAntistress: string
		catSoundSleep: string
		catWomensHealth: string
		catMensStrength: string
		catGoldenAge: string
		catSpecializedSupport: string
		womensHealth: string
		productsCount: (values: TranslationValues) => string
		moreProducts: string
		viewAll: string
		allCourses: string
		academyTitle: string
		biohacking: string
		vitaminsNutrition: string
		emotionalIntelligence: string
		balancedNutrition: string
		retreatCenter: string
		detailsShort: string
		visitShopTitle: string
		toShop: string
		allReviews: string
		volumeMl: string
		inStock: string
		getConsultation: string
	}
	'about': {
		breadcrumb: string
		igorTitle: string
		resultsTitle: string
		top3Trader: string
		top3TraderDesc: string
		profit80: string
		profit80Desc: string
		marketplacePre: string
		marketplace: string
		marketplaceDesc: string
		accuracy95: string
		accuracy95Desc: string
		missionText: string
		workWithTitle: string
		workWith1: string
		workWith2: string
		workWith3: string
		dontKnowStart: string
		aiHelp: string
		goToInterview: string
		eduardTitle: string
		eduardPath1: string
		eduardPath2: string
		eduardRealityTitle: string
		realityItem1: string
		realityItem2: string
		realityItem3: string
		realityItem4: string
		eduardNotGiveUp: string
		eduardStudied: string
		eduardNowStable: string
		eduardFoundation1: string
		eduardFoundation2: string
		pantheonXTitle: string
		pantheonXItem1: string
		pantheonXItem2: string
		pantheonXItem3: string
		pantheonXItem4: string
		finalCta1: string
		finalCta2: string
		finalCta3: string
		igorBio: (values: RichValues) => ReactNode
	}
	'privacy': {
		title: string
		lastUpdated: string
		intro: string
		section1Title: string
		section1Intro: string
		section1Label1: string
		section1Text1: string
		section1Label2: string
		section1Text2: string
		section1Label3: string
		section1Text3: string
		section1Label4: string
		section1Text4: string
		section1Label5: string
		section1Text5: string
		section2Title: string
		section2Intro: string
		section2Item1: string
		section2Item2: string
		section2Item3: string
		section2Item4: string
		section2Item5: string
		section2Item6: string
		section3Title: string
		section3Body: string
		section4Title: string
		section4Body: string
		section5Title: string
		section5Intro: string
		section5Item1: string
		section5Item2: string
		section5Item3: string
		section6Title: string
		section6Body: string
		section7Title: string
		section7Intro: string
		section7Item1: string
		section7Item2: string
		section7Item3: string
		section7Item4: string
		section7Item5: string
		section7Item6: string
		section8Title: string
		section8Body: string
		section9Title: string
		section9Body: string
		section10Title: string
		section10Body: string
	}
	'contacts': {
		breadcrumbTitle: string
		title: string
		addressLabel: string
		address: string
		phoneLabel: string
		phone: string
		hours: string
		emailLabel: string
		email: string
		socialLabel: string
		consultTitle: string
		namePlaceholder: string
		phonePlaceholder: string
		emailPlaceholder: string
		messagePlaceholder: string
		submit: string
		mapAlt: string
	}
	'webinars': {
		loadingError: string
		tryRefresh: string
		noWebinars: string
		title: string
		subtitle: string
	}
	'paywall': {
		breadcrumbTitle: string
		title: string
		featureModules: string
		featureWorkbook: string
		featureWorkshops: string
		featureAiAgents: string
		featureScreener: string
		featureIndicators: string
		featureBlog: string
		oldPrice: string
		price: string
		priceUntil: string
		sixMonths: string
		oneYear: string
		featureAll: string
		featureIncluded: string
		featureAllMeetings: string
		featureUnlimitedRequests: string
		featureUnlimited: string
		featureBlogUnlim: string
		purchase: string
		paymentError: (values: TranslationValues) => string
		gatewayError: (values: TranslationValues) => string
		serverError: string
		unexpectedError: string
		noPaymentUrl: string
		oldPriceMonth: string
		priceMonth: string
		oneMonth: string
		threeMonths: string
		featureForPay: string
		featureMonthMeetings: string
		featureLimitedRequests: string
		validationFallback: string
		gatewayFallback: string
	}
	'payments': {
		verifyingPayment: string
		autoRedirect: string
		successTitle: string
		errorTitle: string
		pendingTitle: string
		loadingTitle: string
		defaultMessage: string
		successActivated: string
		goToSubscriptions: string
		goToCourses: string
		tryAgain: string
		mySubscriptions: string
		goToCabinet: string
		goToPayment: string
		myCabinet: string
		contactSupport: string
		pageLoading: string
		pageLoadingDesc: string
	}
	'cabinet.studyPlatform': {
		breadcrumbTitle: string
		pageTitle: string
		filterAll: string
		filterMyCourses: string
		findCourseAi: string
		lectureCount: (values: TranslationValues) => string
		moreDetails: string
		loadingCourses: string
		loading: string
		breadcrumbHome: string
		breadcrumbAcademy: string
		breadcrumbAcademyVb: string
		breadcrumbCourse: string
		goalLabel: string
		learningProgress: string
		purchased: string
		courseCost: string
		purchase: string
		hasPromoCode: string
		enterPromoCode: string
		withoutPromoCode: string
		back: string
		closeLabel: string
		enterPromoCodeTitle: string
		promoPlaceholder: string
		checkPromoCode: string
		checking: string
		changePromoCode: string
		promoValid: (values: TranslationValues) => string
		freeCourse: string
		newPrice: string
		getFree: string
		proceedToPay: string
		modulesList: string
		courseAddedFree: string
		promoInvalid: string
		promoCheckError: string
		lessonsCount: (values: TranslationValues) => string
		videoTooltip: string
		presentationTooltip: string
		quizTooltip: string
		breadcrumbLesson: string
		lessonTopics: string
		contentInDev: string
		pdfMaterial: string
		docMaterial: string
		xlsxMaterial: string
		download: string
		completeWithQuiz: string
		takeQuiz: string
		breadcrumbQuiz: string
		quizAlreadyPassed: string
		quizPassedDesc: string
		mentorComment: string
		textAnswerPlaceholder: string
		noQuestions: string
		quizCompleted: string
		finishQuiz: string
		quizPassed: string
		alreadyAttempted: string
		quizError: string
	}
	'cabinet.common': {
		pageTitle: string
		personalData: string
		academy: string
		certificates: string
		subscriptions: string
		algoTrading: string
		screener: string
		webinars: string
		settings: string
		logout: string
		navigation: string
	}
	'cabinet.personalData': {
		breadcrumbTitle: string
		pageTitle: string
		sectionTitle: string
		contactInfo: string
		firstNamePlaceholder: string
		lastNamePlaceholder: string
		phonePlaceholder: string
		solanaPlaceholder: string
		solanaHint: string
		save: string
	}
	'cabinet.subscriptions': {
		breadcrumbTitle: string
		pageTitle: string
		loadError: string
		loadErrorHint: string
		noSubscriptionsTitle: string
		noSubscriptionsDesc: string
		goToPaywall: string
		activeSubscriptionsTitle: string
		monthly: string
		yearly: string
		expired: string
		active: string
		startDate: string
		endDate: string
		paymentAmount: string
		duration: (values: TranslationValues) => string
		paymentStatus: string
		paid: string
		pending: string
		declined: string
		renewSubscription: string
	}
	'cabinet.certificates': {
		breadcrumbTitle: string
		pageTitle: string
		tabCourses: string
		tabMyCertificates: string
		loadError: string
		noCertificatesTitle: string
		noCertificatesDesc: string
		myCertificatesTitle: (values: TranslationValues) => string
		statusConfirmed: string
		statusIssued: string
		statusPending: string
		view: string
		download: string
		metadata: string
		loadingCourses: string
		noCoursesTitle: string
		noCoursesHint: string
		purchased: string
		notPurchased: string
		courseProgress: (values: TranslationValues) => string
		overallProgress: string
		courseModules: string
		accessible: string
		partial: string
		locked: string
		free: string
		getCertificate: string
		generating: string
		buyCourse: string
		completeModule: string
		lessonsList: string
		modalTitle: string
		modalDesc: string
		fieldFirstName: string
		fieldLastName: string
		fieldSolanaWallet: string
		solanaInfoTitle: string
		solanaInfoDesc: string
		cancel: string
		fillData: string
	}
	'cabinet.settings': {
		breadcrumbTitle: string
		pageTitle: string
		sectionTitle: string
		changePassword: string
		currentPasswordPlaceholder: string
		newPasswordPlaceholder: string
		confirmPasswordPlaceholder: string
		changePasswordBtn: string
		changeLogin: string
		newEmailPlaceholder: string
		passwordConfirmPlaceholder: string
		changeEmailBtn: string
		dangerZoneTitle: string
		dangerZoneDesc: string
		deleteAccountBtn: string
		deleteModalTitle: string
		deleteModalDesc: string
		deletePasswordPlaceholder: string
		cancelBtn: string
		deleteForeverBtn: string
	}
	'cabinet.webinars': {
		breadcrumbTitle: string
		pageTitle: string
		loadError: string
		tryRefresh: string
		noWebinars: string
		title: string
		total: (values: TranslationValues) => string
		active: string
		inactive: string
		monthlyBadge: string
		yearlyBadge: string
		cancelPurchase: string
		watch: string
		buy: string
		paymentError: string
		cancelSuccess: string
		cancelError: string
	}
	'screener': {
		title: string
		terminal: string
		backToScreener: string
		pairNotFound: (values: TranslationValues) => string
		loading: string
		filters: {
			searchPlaceholder: string
		}
		table: {
			pair: string
			priceAndChange: string
			noPairs: string
		}
		feed: {
			bigTrades: string
			time: string
			price: string
			size: string
			loadingTrades: string
			noTrades: string
			waitingVolumes: string
		}
		tooltips: {
			dragResizeColumn: string
			toggleColumns: string
			dragResizeChart: string
			dragResizeChartWidth: string
			toggleIndicator: (values: TranslationValues) => string
		}
	}
	'aiAgent': {
		greeting: string
		breadcrumb: string
		inputPlaceholder: string
		deleteChat: string
		limitError: string
		requestError: (values: TranslationValues) => string
		unexpectedError: string
		deleteTitle: string
		confirmYes: string
		confirmNo: string
	}
	'tradingChat': {
		expertBadge: string
		title: string
		subtitle: string
		forWhoTitle: string
		forWho1: string
		forWho2: string
		forWho3: string
		applyButton: string
		tagline: string
		learnMoreTitle: string
		chatPresentationTitle: string
		joinButton: string
		insideTitle: string
		feature1: string
		feature2: string
		feature3: string
		feature4: string
		feature5: string
		resultsTitle: string
		result1: string
		result2: string
		result3: string
		result4: string
		result5: string
		result6: string
		supportChat: string
	}
}

export type Namespace = keyof MessageShapes
