#!/usr/bin/env node
/**
 * Generates src/i18n/t-keys.ts from src/i18n/messages/uk.json.
 * uk.json is the source of truth; never hand-edit t-keys.ts.
 *
 * Classification (mirrored at runtime by src/lib/contexts/translations/wrap.ts):
 *  - rich:  message contains a tag like <link>…</link>  -> (values: RichValues) => ReactNode
 *  - args:  message contains an ICU argument {name}     -> (values: TranslationValues) => string
 *  - plain: everything else                              -> string
 * A JSON node is a namespace if any direct child is a string; otherwise a group.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ICU_ARGS = /\{\s*[0-9a-zA-Z_]+/
const RICH_TAG = /<[a-zA-Z][^>]*>/

export function leafType(message) {
	if (RICH_TAG.test(message)) return 'rich'
	if (ICU_ARGS.test(message)) return 'args'
	return 'plain'
}

export function isNamespace(node) {
	return Object.values(node).some((v) => typeof v === 'string')
}

export function buildTKeys(node, prefix = '') {
	const out = {}
	for (const [k, v] of Object.entries(node)) {
		if (typeof v === 'string') continue
		const p = prefix ? `${prefix}.${k}` : k
		out[k] = isNamespace(v) ? p : buildTKeys(v, p)
	}
	return out
}

export function collectNamespaces(node, prefix = '') {
	const out = []
	for (const [k, v] of Object.entries(node)) {
		if (typeof v === 'string') continue
		const p = prefix ? `${prefix}.${k}` : k
		if (isNamespace(v)) out.push([p, v])
		else out.push(...collectNamespaces(v, p))
	}
	return out
}

const identRe = /^[A-Za-z_$][A-Za-z0-9_$]*$/

function serializeTKeys(node, indent = '') {
	const lines = ['{']
	for (const [k, v] of Object.entries(node)) {
		const key = identRe.test(k) ? k : `'${k}'`
		if (typeof v === 'string') lines.push(`${indent}\t${key}: '${v}',`)
		else lines.push(`${indent}\t${key}: ${serializeTKeys(v, indent + '\t')},`)
	}
	lines.push(`${indent}}`)
	return lines.join('\n')
}

function shapeType(node, indent = '\t') {
	const lines = ['{']
	for (const [k, v] of Object.entries(node)) {
		const key = identRe.test(k) ? k : `'${k}'`
		if (typeof v === 'string') {
			const kind = leafType(v)
			if (kind === 'plain') lines.push(`${indent}\t${key}: string`)
			else if (kind === 'args')
				lines.push(`${indent}\t${key}: (values: TranslationValues) => string`)
			else lines.push(`${indent}\t${key}: (values: RichValues) => ReactNode`)
		} else {
			lines.push(`${indent}\t${key}: ${shapeType(v, indent + '\t')}`)
		}
	}
	lines.push(`${indent}}`)
	return lines.join('\n')
}

export function generate(messages) {
	const namespaces = collectNamespaces(messages)
	return `/* AUTO-GENERATED by scripts/generate-t-keys.mjs — DO NOT EDIT.
 * Source of truth: src/i18n/messages/uk.json
 * Regenerate: npm run generate-t-keys
 */
import type { ReactNode } from 'react'

export type TranslationValues = Record<string, string | number | Date>
export type RichValues = Record<
	string,
	string | number | Date | ((chunks: ReactNode) => ReactNode)
>

export const TKeys = ${serializeTKeys(buildTKeys(messages))} as const

export interface MessageShapes {
${namespaces.map(([p, node]) => `\t'${p}': ${shapeType(node, '\t')}`).join('\n')}
}

export type Namespace = keyof MessageShapes
`
}

const isMain =
	process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (isMain) {
	const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
	const messages = JSON.parse(
		fs.readFileSync(path.join(root, 'src/i18n/messages/uk.json'), 'utf8'),
	)
	const outPath = path.join(root, 'src/i18n/t-keys.ts')
	fs.writeFileSync(outPath, generate(messages))
	console.log(`Wrote ${path.relative(process.cwd(), outPath)}`)
}
