name: Build and Deploy to ECR

on:
  push:
    branches: [ main, master, dev ]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DEBUG=False" >> .env
        echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container

    - name: Extract branch name
      shell: bash
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Проверка наличия secrets
      run: |
        echo "🔍 Проверка наличия secrets..."
        
        MISSING=0
        
        if [ -z "${{ secrets.AWS_ACCOUNT_ID }}" ]; then
          echo "❌ Secret AWS_ACCOUNT_ID не задан!"
          MISSING=1
        fi
        
        if [ -z "${{ secrets.ECR_REPOSITORY_NAME }}" ]; then
          echo "❌ Secret ECR_REPOSITORY_NAME не задан!"
          MISSING=1
        fi
        
        if [ -z "${{ secrets.AWS_REGION }}" ]; then
          echo "❌ Secret AWS_REGION не задан!"
          MISSING=1
        fi
        
        if [ "$MISSING" -eq 1 ]; then
          echo "🚫 Остановка: один или несколько secrets отсутствуют."
          exit 1
        fi
        
        echo "✅ Все необходимые secrets присутствуют."
    

    - name: check ECR tag values
      run: |
        echo "Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"
        echo "Region: ${{ secrets.AWS_REGION }}"
        echo "Repository: ${{ secrets.ECR_REPOSITORY_NAME }}"
        echo "Branch: ${{ env.BRANCH_NAME }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ github.sha }}
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ env.BRANCH_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=False
          ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
          STAGE=${{ vars[format('STAGE_{0}', github.ref_name)] }}

    - name: Output image URI
      run: |
        echo "Image URIs:"
        echo "- SHA: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ github.sha }}"
        echo "- Latest: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest"
        echo "- Branch: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ env.BRANCH_NAME }}"
    
