name: Build and Deploy to ECR

on:
  push:
    branches: [ main, master, dev ]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Проверка наличия secrets
      run: |
        echo "🔍 Проверка наличия secrets..."
        
        MISSING=0
        
        if [ -z "${{ secrets.AWS_ACCOUNT_ID }}" ]; then
          echo "❌ Secret AWS_ACCOUNT_ID не задан!"
          MISSING=1
        fi
        
        if [ -z "${{ secrets.ECR_REPOSITORY_NAME }}" ]; then
          echo "❌ Secret ECR_REPOSITORY_NAME не задан!"
          MISSING=1
        fi
        
        if [ -z "${{ secrets.AWS_REGION }}" ]; then
          echo "❌ Secret AWS_REGION не задан!"
          MISSING=1
        fi
        
        if [ "$MISSING" -eq 1 ]; then
          echo "🚫 Остановка: один или несколько secrets отсутствуют."
          exit 1
        fi
        
        echo "✅ Все необходимые secrets присутствуют."
    

    - name: check ECR tag values
      run: |
        echo "Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"
        echo "Region: ${{ secrets.AWS_REGION }}"
        echo "Repository: ${{ secrets.ECR_REPOSITORY_NAME }}"
        echo "Branch: ${{ env.BRANCH_NAME }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ github.sha }}
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ env.BRANCH_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=False
          ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
          STAGE=${{ vars[format('STAGE_{0}', github.ref_name)] }}

    - name: Output image URI
      run: |
        echo "Image URIs:"
        echo "- SHA: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ github.sha }}"
        echo "- Latest: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest"
        echo "- Branch: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ env.BRANCH_NAME }}"
    
